# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_conf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61udio_conf.proto\x12\x0c\x61pollo.audio\"\xae\x01\n\tTopicConf\x12\x1d\n\x15\x61udio_data_topic_name\x18\x01 \x01(\t\x12\"\n\x1a\x61udio_detection_topic_name\x18\x02 \x01(\t\x12\x1f\n\x17localization_topic_name\x18\x03 \x01(\t\x12\x1e\n\x16\x61udio_event_topic_name\x18\x04 \x01(\t\x12\x1d\n\x15perception_topic_name\x18\x05 \x01(\t\"[\n\tAudioConf\x12+\n\ntopic_conf\x18\x01 \x01(\x0b\x32\x17.apollo.audio.TopicConf\x12!\n\x19respeaker_extrinsics_path\x18\x02 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_conf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOPICCONF._serialized_start=35
  _TOPICCONF._serialized_end=209
  _AUDIOCONF._serialized_start=211
  _AUDIOCONF._serialized_end=302
# @@protoc_insertion_point(module_scope)
